# Generated by Django 4.2 on 2024-12-09 09:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses_details", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="roleassignment",
            name="id",
        ),
        migrations.RemoveField(
            model_name="roleassignment",
            name="role_id",
        ),
        migrations.DeleteModel(
            name="Role",
        ),
        migrations.DeleteModel(
            name="RoleAssignment",
        ),
    ]
